#' @title Provide the List of Prefabricated Rodent Datasets
#'
#' @description Create a \code{list} of dataset lists, each used to create a dataset in \code{\link{fill_data}}. \cr \cr
#'              The currently prefabricated datasets include \code{"all"}, \code{"all_interp"}, \code{"controls"}, \code{"controls_interp"}, \code{"exclosures"}, \code{"exclosures_interp"}, \code{"dm_controls"}, and \code{"dm_controls_interp"}. 
#'
#' @return \code{list} of dataset lists, each containing \code{metadata}, \code{fun}, and \code{args} elements -- the latter two of which are used in \code{\link{do.call}} to create data files.
  list(

    all = list(

            metadata = list(
                         name        = "all",
                         description = "classic dataset, all plots combined"),

            fun      = prepare_rodent_dataset,

            args     = list(
                         name        = "all",
                         clean       = FALSE,
                         level       = "Site",
                         type        = "Rodents",
                         plots       = "all",
                         treatment   = NULL,
                         unknowns    = FALSE,
                         shape       = "crosstab",
                         time        = "newmoon",
                         output      = "abundance",
                         fillweight  = FALSE,
                         na_drop     = FALSE,
                         zero_drop   = FALSE,
                         min_traps   = 1,
                         min_plots   = 24,
                         species     = base_species(),
                         total       = TRUE,
                         effort      = TRUE,
                         interpolate = FALSE)),

    all_interp = list(


            metadata = list(
                         name        = "all_interp",
                         description = "classic dataset, all plots combined, interpolated for models that cannot have missing data"),

            fun      = prepare_rodent_dataset,

            args     = list(
                         name        = "all_interp",
                         clean       = FALSE,
                         level       = "Site",
                         type        = "Rodents",
                         plots       = "all",
                         treatment   = NULL,
                         unknowns    = FALSE,
                         shape       = "crosstab",
                         time        = "newmoon",
                         output      = "abundance",
                         fillweight  = FALSE,
                         na_drop     = FALSE,
                         zero_drop   = FALSE,
                         min_traps   = 1,
                         min_plots   = 24,
                         species     = base_species(),
                         total       = TRUE,
                         effort      = TRUE,
                         interpolate = TRUE)),
    controls = 
         list(metadata = list(),
              fun = prepare_rodent_dataset,
              args = list(name = "controls",
                          clean = FALSE,
                          level = "Treatment",
                          type = "Rodents",
                          plots = "Longterm",
                          treatment = "control",
                          unknowns = FALSE,
                          shape = "crosstab",
                          time = "newmoon",
                          output = "abundance",
                          fillweight = FALSE,
                          na_drop = FALSE,
                          zero_drop = FALSE,
                          min_traps = 1,
                          min_plots = 24,
                          species = base_species(),
                          total = TRUE,
                          effort = TRUE,
                          interpolate = FALSE)),

    controls_interp = 
         list(metadata = list(),
              fun = prepare_rodent_dataset,
              args = list(name = "controls_interp",
                          clean = FALSE,
                          level = "Treatment",
                          type = "Rodents",
                          plots = "Longterm",
                          treatment = "control",
                          unknowns = FALSE,
                          shape = "crosstab",
                          time = "newmoon",
                          output = "abundance",
                          fillweight = FALSE,
                          na_drop = FALSE,
                          zero_drop = FALSE,
                          min_traps = 1,
                          min_plots = 24,
                          species = base_species(),
                          total = TRUE,
                          effort = TRUE,
                          interpolate = TRUE)),

    exclosures = 
         list(metadata = list(),
              fun = prepare_rodent_dataset,
              args = list(name = "exclosures",
                          clean = FALSE,
                          level = "Treatment",
                          type = "Rodents",
                          plots = "Longterm",
                          treatment = "exclosure",
                          unknowns = FALSE,
                          shape = "crosstab",
                          time = "newmoon",
                          output = "abundance",
                          fillweight = FALSE,
                          na_drop = FALSE,
                          zero_drop = FALSE,
                          min_traps = 1,
                          min_plots = 24,
                          species = base_species(),
                          total = TRUE,
                          effort = TRUE,
                          interpolate = FALSE)),

    exclosures_interp = 
         list(metadata = list(),
              fun = prepare_rodent_dataset,
              args = list(name = "exclosures_interp",
                          clean = FALSE,
                          level = "Treatment",
                          type = "Rodents",
                          plots = "Longterm",
                          treatment = "exclosure",
                          unknowns = FALSE,
                          shape = "crosstab",
                          time = "newmoon",
                          output = "abundance",
                          fillweight = FALSE,
                          na_drop = FALSE,
                          zero_drop = FALSE,
                          min_traps = 1,
                          min_plots = 24,
                          species = base_species(),
                          total = TRUE,
                          effort = TRUE,
                          interpolate = TRUE)),


    dm_controls = 
         list(metadata = list(),
              fun = prepare_rodent_dataset,
              args = list(name = "dm_controls",
                          clean = FALSE,
                          level = "Treatment",
                          type = "Rodents",
                          plots = "Longterm",
                          treatment = "control",
                          unknowns = FALSE,
                          shape = "crosstab",
                          time = "newmoon",
                          output = "abundance",
                          fillweight = FALSE,
                          na_drop = FALSE,
                          zero_drop = FALSE,
                          min_traps = 1,
                          min_plots = 24,
                          species = "DM",
                          total = FALSE,
                          effort = TRUE,
                          interpolate = FALSE)),

    dm_controls_interp = 
         list(metadata = list(),
              fun = prepare_rodent_dataset,
              args = list(name = "dm_controls_interp",
                          clean = FALSE,
                          level = "Treatment",
                          type = "Rodents",
                          plots = "Longterm",
                          treatment = "control",
                          unknowns = FALSE,
                          shape = "crosstab",
                          time = "newmoon",
                          output = "abundance",
                          fillweight = FALSE,
                          na_drop = FALSE,
                          zero_drop = FALSE,
                          min_traps = 1,
                          min_plots = 24,
                          species = "DM",
                          total = FALSE,
                          effort = TRUE,
                          interpolate = TRUE)))
