context("Test utilities functions")

test_that("dataout", {
  df <- data.frame(x = 1:10, y = 11:20)
  dfo <- dataout(df, moons_options(save = FALSE))
  fp <- file_path(dirtree(main = ""), "ok.csv")
  fp1 <- gsub("ok.csv", "", fp)
  fp2 <- paste0(fp1, "data")
  dir.create(fp2)
  options_list <- moons_options(tree = dirtree(main = ""), 
                                filename = "ok.csv")
  dfo2 <- dataout(df, options_list)
  df <- classy(df, c("moons", "data.frame"))
  expect_error(dataout(1, moons_options()))
  expect_equal(dfo, df)
  expect_equal(dfo2, df)
  unlink(fp2, recursive = TRUE, force = TRUE)
})

test_that("append_csv", {
  df <- data.frame(x = 1:10, y = 11:20)
  expect_error(append_csv(10, "ok.csv"))
  expect_error(append_csv(df, c("ok", "ok")))
  expect_error(append_csv(df, 10))
  expect_silent(append_csv(df, "ok.csv"))
  unlink("ok.csv")
})

test_that("fcast0", {
  expect_is(fcast0(1), "list")
  expect_equal(length(fcast0(1)), 2)
  expect_equal(length(fcast0(1)[[1]]), 1)
  expect_equal(length(fcast0(10)[[1]]), 10)
  expect_equal(nrow(fcast0(1)[[2]]), 1)
  expect_equal(nrow(fcast0(10)[[2]]), 10)
  expect_error(fcast0(1.5))
  expect_error(fcast0(1:10))
  expect_error(fcast0(1, c("ok", "ok")))
  expect_error(fcast0("ok"))
  expect_error(fcast0(1, 1))
})

test_that("today", {
  expect_equal(today(), Sys.Date())
  expect_equal(round(today(time = TRUE), "secs"), round(Sys.time(), "secs"))
})

test_that("classy", {
  expect_error(classy(1, 1))
  expect_is(classy(1, "character"), "character")
  expect_is(classy(1, c("ok", "character")), c("character"))
  expect_is(classy(1, c("ok", "character")), c("ok"))
})

test_that("remove_incompletes", {
  df <- data.frame(ok = 1:10, not_ok = 11:20)
  expect_error(remove_incompletes(1, "ok"))
  expect_error(remove_incompletes(df, 1))
  expect_error(remove_incompletes(df, "ok2"))
  expect_error(remove_incompletes(df, c("ok", "ok")))
  expect_is(remove_incompletes(df, "ok"), "data.frame")
})

test_that("na_conformer", {
  expect_silent(nac <- na_conformer(NA))
  expect_equal(nac, "NA")
  df <- data.frame(ok = NA)
  expect_silent(na_conformer(df, "ok"))
  expect_error(na_conformer(as.matrix(1)))
})

tree <- dirtree(main = "testing_casting");
metadata <- read_data(tree, "metadata")
cast_date <- as.Date(metadata$forecast_date)

test_that("check_args", {
  expect_error(check_args(base = c("ok", "ok")))
  expect_error(check_args(main = c("ok", "ok")))
  expect_error(check_args(base = 1))
  expect_error(check_args(main = 1))
  expect_error(check_args(subs = "ok"))
  expect_error(check_args(quiet = 1))
  expect_error(check_args(quiet = c(TRUE, FALSE)))
  expect_error(check_args(cast_date = 1))
  expect_error(check_args(cast_date = c(today(), today())))
  expect_error(check_args(append_missing_to_raw = 1))
  expect_error(check_args(append_missing_to_raw = c(TRUE, FALSE)))
  expect_error(check_args(m_save = 1))
  expect_error(check_args(m_save = c(TRUE, FALSE)))
  expect_error(check_args(start = NULL))
  expect_error(check_args(start = "a"))
  expect_error(check_args(start = c(1, 2)))
  expect_error(check_args(start = 1.5))
  expect_error(check_args(end = "a"))
  expect_error(check_args(end = 1.5))
  expect_error(check_args(hind_step = NULL))
  expect_error(check_args(hind_step = "a"))
  expect_error(check_args(hind_step = c(1, 2)))
  expect_error(check_args(hind_step = 1.5))
  expect_error(check_args(drop_spp = 1))
  expect_error(check_args(min_plots = NULL))
  expect_error(check_args(min_plots = "a"))
  expect_error(check_args(min_plots = c(1, 2)))
  expect_error(check_args(min_plots = 1.5))
  expect_error(check_args(min_traps = NULL))
  expect_error(check_args(min_traps = "a"))
  expect_error(check_args(min_traps = c(1, 2)))
  expect_error(check_args(min_traps = 1.5))
  expect_error(check_args(treatment = 1))
  expect_error(check_args(level = 1))
  expect_error(check_args(output = 1))
  expect_error(check_args(plots = "ok"))
  expect_error(check_args(r_save = 1))
  expect_error(check_args(r_save = c(TRUE, TRUE)))
  expect_error(check_args(r_filename = 1))
  expect_error(check_args(r_filename = c("ok.csv", "ok.csv")))
  expect_error(check_args(cov_fcast = 1))
  expect_error(check_args(cov_fcast = c(TRUE, FALSE)))
  expect_error(check_args(cov_hist = 1))
  expect_error(check_args(cov_hist = c(TRUE, FALSE)))
  expect_error(check_args(yr = NULL))
  expect_error(check_args(yr = "a"))
  expect_error(check_args(yr = c(1, 2)))
  expect_error(check_args(yr = 1.5))
  expect_error(check_args(min_lag = NULL))
  expect_error(check_args(min_lag = "a"))
  expect_error(check_args(min_lag = c(1, 2)))
  expect_error(check_args(min_lag = 1.5))
  expect_error(check_args(lead_time = NULL))
  expect_error(check_args(lead_time = "a"))
  expect_error(check_args(lead_time = c(1, 2)))
  expect_error(check_args(lead_time = 1.5))
  expect_error(check_args(fcast_nms = "a"))
  expect_error(check_args(fcast_nms = c(1, 2.5)))
  expect_error(check_args(fcast_nms = 1.5))
  expect_error(check_args(nfcnm = "a"))
  expect_error(check_args(nfcnm = c(1, 2)))
  expect_error(check_args(nfcnm = 1.5))
  expect_error(check_args(append_fcast_csv = 1))
  expect_error(check_args(append_fcast_csv = c(TRUE, TRUE)))
  expect_error(check_args(c_save = 1))
  expect_error(check_args(c_save = c(TRUE, TRUE)))
  expect_error(check_args(meta_save = 1))
  expect_error(check_args(meta_save = c(TRUE, TRUE)))
  expect_error(check_args(download_existing_predictions = 1))
  expect_error(check_args(download_existing_predictions = 
                                  c(TRUE, TRUE)))
  expect_error(check_args(ensemble = 1))
  expect_error(check_args(ensemble = c(TRUE, TRUE)))
  expect_error(check_args(from_zenodo = 1))
  expect_error(check_args(from_zenodo = c(TRUE, TRUE)))
  expect_error(check_args(hist_fcast_file = 1))
  expect_error(check_args(hist_fcast_file = c("ok.csv", "ok.csv")))
  expect_error(check_args(c_filename = 1))
  expect_error(check_args(c_filename = c("ok.csv", "ok.csv")))
  expect_error(check_args(meta_filename = 1))
  expect_error(check_args(meta_filename = c("ok.csv", "ok.csv")))
  expect_error(check_args(m_filename = 1))
  expect_error(check_args(m_filename = c("ok.csv", "ok.csv")))
  expect_error(check_args(source_name = 1))
  expect_error(check_args(source_name = c("ok", "ok")))
  expect_error(check_args(cast_type = 1))
  expect_error(check_args(cast_type = c("forecasts", "forecasts")))
  expect_error(check_args(cast_type = "ok"))
  expect_error(check_args(version = 1))
  expect_error(check_args(version = c("latest", "latest")))
  expect_error(check_args(confidence_level = "a"))
  expect_error(check_args(confidence_level = c(0.1, 0.2)))
  expect_error(check_args(confidence_level = 1.5))
  expect_error(check_args(confidence_level = -0.5))
  expect_error(check_args(model = "AutoArima"))
  expect_error(check_args(tmnt_type = "ok"))
  expect_error(check_args(n_future_moons = "a"))
  expect_error(check_args(n_future_moons = c(1, 2)))
  expect_error(check_args(n_future_moons = 1.5))
  expect_error(check_args(save = 1))
  expect_error(check_args(save = c(TRUE, FALSE)))
  expect_error(check_args(filename = 1))
  expect_error(check_args(filename = c("ok.csv", "ok.csv")))
  expect_error(check_args(tree = 1))
  expect_error(check_args(options_all = 1))
  expect_error(check_args(options_dir = 1))
  expect_error(check_args(options_PortalData = 1))
  expect_error(check_args(options_data = 1))
  expect_error(check_args(options_predictions = 1))
  expect_error(check_args(options_models = 1))
  expect_error(check_args(path = 1))
  expect_error(check_args(toggle = "1sp"))
  expect_error(check_args(cast_dates = 1))
  expect_error(check_args(min_observed = 1.5))
  expect_error(check_args(min_observed = "ok"))
  expect_error(check_args(min_observed = 1:5))
  expect_error(check_args(ndates = 1.5))
  expect_error(check_args(ndates = "ok"))
  expect_error(check_args(ndates = 1:5))
  expect_error(check_args(from_date = 1))
  expect_error(check_args(from_date = rep(cast_date, 2)))
  expect_error(check_args(with_census = 1))
  expect_error(check_args(with_census = rep(TRUE, 2)))
  expect_error(check_args(rangex = rep("ok", 2)))
  expect_error(check_args(rangex = 1:3))
  expect_error(check_args(rangex = c(300.1, 410)))
  expect_error(check_args(add_obs = 1))
  expect_error(check_args(add_obs = rep(TRUE, 2)))
  expect_error(check_args(start_newmoon = 0))
  expect_error(check_args(start_newmoon = 1:2))
  expect_error(check_args(start_newmoon = 1.5))

})