prefab_rodent_dataset_controls <- function(interpolate = NULL) {
  out <- list(
    all                = list(metadata = list(name       = "all", 
                                              descriptor = "classic dataset, all plots combined"),
                              fun      = "prep_rodent_dataset",
                              args     = list(name        = "all", 
                                              species     = base_species(), 
                                              total       = TRUE,
                                              interpolate = FALSE, 
                                              clean       = FALSE, 
                                              type        = "Rodents", 
                                              level       = "Site", 
                                              plots       = "all", 
                                              treatment   = NULL, 
                                              min_plots   = 24, 
                                              min_traps   = 1, 
                                              output      = "abundance", 
                                              fillweight  = FALSE, 
                                              unknowns    = FALSE, 
                                              time        = "newmoon", 
                                              na_drop     = FALSE, 
                                              zero_drop   = TRUE, 
                                              effort      = TRUE,
                                              filename    = "rodents_all.csv")),
    all_interp         = list(metadata = list(name = "all_interp", 
                                              descriptor = "classic dataset, all plots combined, interpolated for models that cannot have missing data"),
                              fun      = "prep_rodent_dataset",
                              args     = list(name        = "all_interp", 
                                              species     = base_species(), 
                                              total       = TRUE,
                                              interpolate = TRUE, 
                                              clean       = FALSE, 
                                              type        = "Rodents", 
                                              level       = "Site", 
                                              plots       = "all", 
                                              treatment   = NULL, 
                                              min_plots   = 24, 
                                              min_traps   = 1,
                                              output      = "abundance", 
                                              fillweight  = FALSE, 
                                              unknowns    = FALSE, 
                                              time        = "newmoon", 
                                              na_drop     = FALSE, 
                                              zero_drop   = TRUE, 
                                              effort      = TRUE, 
                                              filename    = "rodents_all_interp.csv")),
    controls           = list(metadata = list(name = "controls", 
                                              descriptor = "classic dataset, control plots combined"),
                              fun      = "prep_rodent_dataset",
                              args     = list(name        = "controls", 
                                              species     = base_species(), 
                                              total       = TRUE, 
                                              interpolate = FALSE, 
                                              clean       = FALSE, 
                                              type        = "Rodents", 
                                              level       = "Treatment", 
                                              plots       = "Longterm", 
                                              treatment   = "control", 
                                              min_plots   = 24, 
                                              min_traps   = 1, 
                                              output      = "abundance", 
                                              fillweight  = FALSE, 
                                              unknowns    = FALSE, 
                                              time        = "newmoon", 
                                              na_drop     = FALSE, 
                                              zero_drop   = TRUE, 
                                              effort      = TRUE, 
                                              filename    = "rodents_controls.csv")),
    controls_interp    = list(metadata = list(name = "controls_interp", 
                                              descriptor = "classic dataset, control plots combined, interpolated for models that cannot have missing data"),
                              fun      = "prep_rodent_dataset",
                              args     = list(name        = "controls_interp", 
                                              species     = base_species(), 
                                              total       = TRUE, 
                                              interpolate = TRUE, 
                                              clean       = FALSE, 
                                              type        = "Rodents", 
                                              level       = "Treatment", 
                                              plots       = "Longterm", 
                                              treatment   = "control", 
                                              min_plots   = 24, 
                                              min_traps   = 1, 
                                              output      = "abundance", 
                                              fillweight  = FALSE, 
                                              unknowns    = FALSE, 
                                              time        = "newmoon", 
                                              na_drop     = FALSE, 
                                              zero_drop   = TRUE, 
                                              effort      = TRUE, 
                                              filename    = "rodents_controls_interp.csv")),
    exclosures         = list(metadata = list(name = "exclosures", 
                                              descriptor = "classic dataset, exclosure plots combined"),
                              fun      = "prep_rodent_dataset",
                              args     = list(name        = "exclosures", 
                                              species     = base_species(), 
                                              total       = TRUE,  
                                              interpolate = FALSE, 
                                              clean       = FALSE, 
                                              type        = "Rodents",  
                                              level       = "Treatment", 
                                              plots       = "Longterm",  
                                              treatment   = "exclosure", 
                                              min_plots   = 24,  
                                              min_traps   = 1, 
                                              output      = "abundance",  
                                              fillweight  = FALSE, 
                                              unknowns    = FALSE,  
                                              time        = "newmoon", 
                                              na_drop     = FALSE, 
                                              zero_drop   = TRUE, 
                                              effort      = TRUE, 
                                              filename    = "rodents_exclosures.csv")),
    exclosures_interp  = list(metadata = list(name = "exclosures_interp", 
                                              descriptor = "classic dataset, exclosure plots combined, interpolated for models that cannot have missing data"),
                              fun      = "prep_rodent_dataset",
                              args     = list(name        = "exclosures_interp", 
                                              species     = base_species(), 
                                              total       = TRUE,  
                                              interpolate = TRUE, 
                                              clean       = FALSE, 
                                              type        = "Rodents",  
                                              level       = "Treatment", 
                                              plots       = "Longterm",  
                                              treatment   = "exclosure", 
                                              min_plots   = 24,  
                                              min_traps   = 1, 
                                              output      = "abundance",  
                                              fillweight  = FALSE, 
                                              unknowns    = FALSE,  
                                              time        = "newmoon", 
                                              na_drop     = FALSE, 
                                              zero_drop   = TRUE, 
                                              effort      = TRUE, 
                                              filename    = "rodents_exclosures_interp.csv")),
    dm_controls        = list(metadata = list(name = "dm_controls", 
                                              descriptor = "DM only, control plots combined"),
                              fun      = "prep_rodent_dataset",
                              args     = list(name        = "dm_controls",  
                                              species     = "DM", 
                                              total       = FALSE,  
                                              interpolate = FALSE, 
                                              clean       = FALSE, 
                                              type        = "Rodents",  
                                              level       = "Treatment", 
                                              plots       = "Longterm",  
                                              treatment   = "control", 
                                              min_plots   = 24,  
                                              min_traps   = 1, 
                                              output      = "abundance",  
                                              fillweight  = FALSE, 
                                              unknowns    = FALSE,  
                                              time        = "newmoon", 
                                              na_drop     = FALSE, 
                                              zero_drop   = TRUE, 
                                              effort      = TRUE, 
                                              filename    = "rodents_dm_controls.csv")),
    dm_controls_interp = list(metadata = list(name = "dm_controls_interp",  
                                              descriptor = "DM only, control plots combined, interpolated for models that cannot have missing data"),
                              fun      = "prep_rodent_dataset",
                              args     = list(name        = "dm_controls_interp",  
                                              species     = "DM", 
                                              total       = FALSE,  
                                              interpolate = TRUE, 
                                              clean       = FALSE, 
                                              type        = "Rodents",  
                                              level       = "Treatment", 
                                              plots       = "Longterm",  
                                              treatment   = "control", 
                                              min_plots   = 24,  
                                              min_traps   = 1, 
                                              output      = "abundance",  
                                              fillweight  = FALSE, 
                                              unknowns    = FALSE,  
                                              time        = "newmoon", 
                                              na_drop     = FALSE, 
                                              zero_drop   = TRUE, 
                                              effort      = TRUE, 
                                              filename    = "rodents_dm_controls_interp.csv")))

  if (is.null(interpolate)) {

    out

  } else {

    dsnames <- names(out)

    if (interpolate) {

      out[grepl("_interp", dsnames)]

    } else {

      out[!grepl("_interp", dsnames)]

    }

  }

}