context("Test options functions")

test_that("all_options", {
  expect_is(all_options(), "all_options")
  expect_is(all_options(cast_type = "hindcasts"), "all_options")
  expect_error(all_options(base = c("ok", "ok")))
  expect_error(all_options(main = c("ok", "ok")))
  expect_error(all_options(base = 1))
  expect_error(all_options(main = 1))
  expect_error(all_options(subs = 1))
  expect_error(all_options(quiet = 1))
  expect_error(all_options(quiet = c(TRUE, FALSE)))
  expect_error(all_options(cast_date = 1))
  expect_error(all_options(cast_date = c(today(), today())))
  expect_error(all_options(append_missing_to_raw = 1))
  expect_error(all_options(append_missing_to_raw = c(TRUE, FALSE)))
  expect_error(all_options(m_save = 1))
  expect_error(all_options(m_save = c(TRUE, FALSE)))
  expect_error(all_options(start = NULL))
  expect_error(all_options(start = "a"))
  expect_error(all_options(start = c(1, 2)))
  expect_error(all_options(start = 1.5))
  expect_error(all_options(end = "a"))
  expect_error(all_options(end = 1.5))
  expect_error(all_options(hind_step = NULL))
  expect_error(all_options(hind_step = "a"))
  expect_error(all_options(hind_step = c(1, 2)))
  expect_error(all_options(hind_step = 1.5))
  expect_error(all_options(drop_spp = 1))
  expect_error(all_options(min_plots = NULL))
  expect_error(all_options(min_plots = "a"))
  expect_error(all_options(min_plots = c(1, 2)))
  expect_error(all_options(min_plots = 1.5))
  expect_error(all_options(min_traps = NULL))
  expect_error(all_options(min_traps = "a"))
  expect_error(all_options(min_traps = c(1, 2)))
  expect_error(all_options(min_traps = 1.5))
  expect_error(all_options(treatment = 1))
  expect_error(all_options(level = 1))
  expect_error(all_options(output = 1))
  expect_error(all_options(plots = "ok"))
  expect_error(all_options(r_save = 1))
  expect_error(all_options(r_save = c(TRUE, TRUE)))
  expect_error(all_options(r_filename = 1))
  expect_error(all_options(r_filename = c("ok.csv", "ok.csv")))
  expect_error(all_options(cov_fcast = 1))
  expect_error(all_options(cov_fcast = c(TRUE, FALSE)))
  expect_error(all_options(cov_hist = 1))
  expect_error(all_options(cov_hist = c(TRUE, FALSE)))
  expect_error(all_options(yr = NULL))
  expect_error(all_options(yr = "a"))
  expect_error(all_options(yr = c(1, 2)))
  expect_error(all_options(yr = 1.5))
  expect_error(all_options(min_lag = NULL))
  expect_error(all_options(min_lag = "a"))
  expect_error(all_options(min_lag = c(1, 2)))
  expect_error(all_options(min_lag = 1.5))
  expect_error(all_options(lead_time = NULL))
  expect_error(all_options(lead_time = "a"))
  expect_error(all_options(lead_time = c(1, 2)))
  expect_error(all_options(lead_time = 1.5))
  expect_error(all_options(fcast_nms = "a"))
  expect_error(all_options(fcast_nms = c(1, 2.5)))
  expect_error(all_options(fcast_nms = 1.5))
  expect_error(all_options(nfcnm = "a"))
  expect_error(all_options(nfcnm = c(1, 2)))
  expect_error(all_options(nfcnm = 1.5))
  expect_error(all_options(append_fcast_csv = 1))
  expect_error(all_options(append_fcast_csv = c(TRUE, TRUE)))
  expect_error(all_options(c_save = 1))
  expect_error(all_options(c_save = c(TRUE, TRUE)))
  expect_error(all_options(meta_save = 1))
  expect_error(all_options(meta_save = c(TRUE, TRUE)))
  expect_error(all_options(download_existing_predictions = 1))
  expect_error(all_options(download_existing_predictions = c(TRUE, TRUE)))
  expect_error(all_options(ensemble = 1))
  expect_error(all_options(ensemble = c(TRUE, TRUE)))
  expect_error(all_options(from_zenodo = 1))
  expect_error(all_options(from_zenodo = c(TRUE, TRUE)))
  expect_error(all_options(hist_fcast_file = 1))
  expect_error(all_options(hist_fcast_file = c("ok.csv", "ok.csv")))
  expect_error(all_options(c_filename = 1))
  expect_error(all_options(c_filename = c("ok.csv", "ok.csv")))
  expect_error(all_options(meta_filename = 1))
  expect_error(all_options(meta_filename = c("ok.csv", "ok.csv")))
  expect_error(all_options(m_filename = 1))
  expect_error(all_options(m_filename = c("ok.csv", "ok.csv")))
  expect_error(all_options(source_name = 1))
  expect_error(all_options(source_name = c("ok", "ok")))
  expect_error(all_options(cast_type = 1))
  expect_error(all_options(cast_type = c("forecasts", "forecasts")))
  expect_error(all_options(cast_type = "ok"))
  expect_error(all_options(version = 1))
  expect_error(all_options(version = c("latest", "latest")))
  expect_error(all_options(confidence_level = "a"))
  expect_error(all_options(confidence_level = c(0.1, 0.2)))
  expect_error(all_options(confidence_level = 1.5))
  expect_error(all_options(confidence_level = -0.5))
  expect_silent(all_options(model = "AutoArima"))
  expect_error(all_options(tmnt_type = "ok"))
  expect_error(all_options(to_cleanup = 1))
  expect_error(all_options(covariate_source = 1))
  expect_error(all_options(covariate_source = "ok"))
  expect_error(all_options(covariate_source = rep("retroactive", 2)))
  expect_error(all_options(covariate_date_made = 1))
  expect_error(all_options(covariate_date_made = rep("ok", 2)))
  expect_is(all_options(model = "AutoArima"), "all_options")
})

test_that("dir_options", {
  expect_is(dir_options(), "dir_options")
  expect_error(dir_options(base = c("ok", "ok")))
  expect_error(dir_options(main = c("ok", "ok")))
  expect_error(dir_options(base = 1))
  expect_error(dir_options(main = 1))
  expect_error(dir_options(subs = 1))
  expect_error(dir_options(quiet = 1))
  expect_error(dir_options(quiet = c(TRUE, FALSE)))
  expect_error(dir_options(to_cleanup = 1))
})

test_that("PortalData_options", {
  expect_is(PortalData_options(), "PortalData_options")
  expect_error(PortalData_options(base = c("ok", "ok")))
  expect_error(PortalData_options(main = c("ok", "ok")))
  expect_error(PortalData_options(base = 1))
  expect_error(PortalData_options(main = 1))
  expect_error(PortalData_options(subs = 1))
  expect_error(PortalData_options(quiet = 1))
  expect_error(PortalData_options(quiet = c(TRUE, FALSE)))
  expect_error(PortalData_options(version = 1))
  expect_error(PortalData_options(version = c("latest", "latest")))
  expect_error(PortalData_options(from_zenodo = 1))
  expect_error(PortalData_options(from_zenodo = c(TRUE, TRUE)))
})

test_that("data_options", {
  expect_is(data_options(), "data_options")
  expect_is(data_options(cast_type = "hindcasts"), "data_options")
  expect_error(data_options(base = c("ok", "ok")))
  expect_error(data_options(main = c("ok", "ok")))
  expect_error(data_options(base = 1))
  expect_error(data_options(main = 1))
  expect_error(data_options(subs = 1))
  expect_error(data_options(quiet = 1))
  expect_error(data_options(quiet = c(TRUE, FALSE)))
  expect_error(data_options(cast_date = 1))
  expect_error(data_options(cast_date = c(today(), today())))
  expect_error(data_options(append_missing_to_raw = 1))
  expect_error(data_options(append_missing_to_raw = c(TRUE, FALSE)))
  expect_error(data_options(m_save = 1))
  expect_error(data_options(m_save = c(TRUE, FALSE)))
  expect_error(data_options(m_filename = 1))
  expect_error(data_options(m_filename = c("ok.csv", "ok.csv")))
  expect_error(data_options(start = NULL))
  expect_error(data_options(start = "a"))
  expect_error(data_options(start = c(1, 2)))
  expect_error(data_options(start = 1.5))
  expect_error(data_options(end = "a"))
  expect_error(data_options(end = 1.5))
  expect_error(data_options(hind_step = NULL))
  expect_error(data_options(hind_step = "a"))
  expect_error(data_options(hind_step = c(1, 2)))
  expect_error(data_options(hind_step = 1.5))
  expect_error(data_options(drop_spp = 1))
  expect_error(data_options(min_plots = NULL))
  expect_error(data_options(min_plots = "a"))
  expect_error(data_options(min_plots = c(1, 2)))
  expect_error(data_options(min_plots = 1.5))
  expect_error(data_options(treatment = 1))
  expect_error(data_options(level = 1))
  expect_error(data_options(output = 1))
  expect_error(data_options(plots = "ok"))
  expect_error(data_options(r_save = 1))
  expect_error(data_options(r_save = c(TRUE, TRUE)))
  expect_error(data_options(r_filename = 1))
  expect_error(data_options(r_filename = c("ok.csv", "ok.csv")))
  expect_error(data_options(cov_fcast = 1))
  expect_error(data_options(cov_fcast = c(TRUE, FALSE)))
  expect_error(data_options(cov_hist = 1))
  expect_error(data_options(cov_hist = c(TRUE, FALSE)))
  expect_error(data_options(yr = NULL))
  expect_error(data_options(yr = "a"))
  expect_error(data_options(yr = c(1, 2)))
  expect_error(data_options(yr = 1.5))
  expect_error(data_options(min_lag = NULL))
  expect_error(data_options(min_lag = "a"))
  expect_error(data_options(min_lag = c(1, 2)))
  expect_error(data_options(min_lag = 1.5))
  expect_error(data_options(lead_time = NULL))
  expect_error(data_options(lead_time = "a"))
  expect_error(data_options(lead_time = c(1, 2)))
  expect_error(data_options(lead_time = 1.5))
  expect_error(data_options(fcast_nms = "a"))
  expect_error(data_options(fcast_nms = c(1, 2.5)))
  expect_error(data_options(fcast_nms = 1.5))
  expect_error(data_options(nfcnm = "a"))
  expect_error(data_options(nfcnm = c(1, 2)))
  expect_error(data_options(nfcnm = 1.5))
  expect_error(data_options(append_fcast_csv = 1))
  expect_error(data_options(append_fcast_csv = c(TRUE, TRUE)))
  expect_error(data_options(hist_fcast_file = 1))
  expect_error(data_options(hist_fcast_file = c("ok.csv", "ok.csv")))
  expect_error(data_options(source_name = 1))
  expect_error(data_options(source_name = c("ok", "ok")))
  expect_error(data_options(c_save = 1))
  expect_error(data_options(c_save = c(TRUE, TRUE)))
  expect_error(data_options(meta_save = 1))
  expect_error(data_options(meta_save = c(TRUE, TRUE)))
  expect_error(data_options(c_filename = 1))
  expect_error(data_options(c_filename = c("ok.csv", "ok.csv")))
  expect_error(data_options(meta_filename = 1))
  expect_error(data_options(meta_filename = c("ok.csv", "ok.csv")))
  expect_error(data_options(cast_type = 1))
  expect_error(data_options(cast_type = c("forecasts", "forecasts")))
  expect_error(data_options(cast_type = "ok"))
  expect_error(data_options(confidence_level = "a"))
  expect_error(data_options(confidence_level = c(0.1, 0.2)))
  expect_error(data_options(confidence_level = 1.5))
  expect_error(data_options(confidence_level = -0.5))
  expect_error(data_options(tmnt_type = "ok"))
  expect_error(data_options(covariate_source = 1))
  expect_error(data_options(covariate_source = "ok"))
  expect_error(data_options(covariate_source = rep("retroactive", 2)))
  expect_error(data_options(covariate_date_made = 1))
  expect_error(data_options(covariate_date_made = rep("ok", 2)))
})

test_that("moons_options", {
  expect_is(moons_options(), "moons_options")
  expect_error(moons_options(n_future_moons = "a"))
  expect_error(moons_options(n_future_moons = c(1, 2)))
  expect_error(moons_options(n_future_moons = 1.5))
  expect_error(moons_options(quiet = 1))
  expect_error(moons_options(quiet = c(TRUE, FALSE)))
  expect_error(moons_options(append_missing_to_raw = 1))
  expect_error(moons_options(append_missing_to_raw = c(TRUE, FALSE)))
  expect_error(moons_options(save = 1))
  expect_error(moons_options(save = c(TRUE, FALSE)))
  expect_error(moons_options(filename = 1))
  expect_error(moons_options(filename = c("ok.csv", "ok.csv")))
  expect_error(moons_options(tree = 1))

})

test_that("rodents_options", {
  expect_is(rodents_options(), "rodents_options")
  expect_is(rodents_options(tmnt_type = "all"), "rodents_options")
  expect_is(rodents_options(tmnt_type = "controls"), "rodents_options")
  expect_error(rodents_options(quiet = 1))
  expect_error(rodents_options(quiet = c(TRUE, FALSE)))
  expect_error(rodents_options(save = 1))
  expect_error(rodents_options(save = c(TRUE, FALSE)))
  expect_error(rodents_options(filename = 1))
  expect_error(rodents_options(filename = c("ok.csv", "ok.csv")))
  expect_error(rodents_options(tree = 1))
  expect_error(rodents_options(start = NULL))
  expect_error(rodents_options(start = "a"))
  expect_error(rodents_options(start = c(1, 2)))
  expect_error(rodents_options(start = 1.5))
  expect_error(rodents_options(end = "a"))
  expect_error(rodents_options(end = 1.5))
  expect_error(rodents_options(hind_step = NULL))
  expect_error(rodents_options(hind_step = "a"))
  expect_error(rodents_options(hind_step = c(1, 2)))
  expect_error(rodents_options(hind_step = 1.5))
  expect_error(rodents_options(drop_spp = 1))
  expect_error(rodents_options(min_plots = NULL))
  expect_error(rodents_options(min_plots = "a"))
  expect_error(rodents_options(min_plots = c(1, 2)))
  expect_error(rodents_options(min_plots = 1.5))
  expect_error(rodents_options(treatment = 1))
  expect_error(rodents_options(level = 1))
  expect_error(rodents_options(output = 1))
  expect_error(rodents_options(plots = "ok"))
  expect_error(rodents_options(cast_type = 1))
  expect_error(rodents_options(cast_type = c("forecasts", "forecasts")))
  expect_error(rodents_options(cast_type = "ok"))
  expect_error(rodents_options(tmnt_type = "ok"))

})

test_that("covariates_options", {
  expect_is(covariates_options(), "covariates_options")
  expect_is(covariates_options(cast_type = "hindcasts"), "covariates_options")
  expect_error(covariates_options(cast_type = 1))
  expect_error(covariates_options(cast_type = c("forecasts", "forecasts")))
  expect_error(covariates_options(cast_type = "ok"))
  expect_error(covariates_options(cov_fcast = 1))
  expect_error(covariates_options(cov_fcast = c(TRUE, FALSE)))
  expect_error(covariates_options(cov_hist = 1))
  expect_error(covariates_options(cov_hist = c(TRUE, FALSE)))
  expect_error(covariates_options(cast_date = 1))
  expect_error(covariates_options(cast_date = c(today(), today())))
  expect_error(covariates_options(yr = NULL))
  expect_error(covariates_options(yr = "a"))
  expect_error(covariates_options(yr = c(1, 2)))
  expect_error(covariates_options(yr = 1.5))
  expect_error(covariates_options(start = NULL))
  expect_error(covariates_options(start = "a"))
  expect_error(covariates_options(start = c(1, 2)))
  expect_error(covariates_options(start = 1.5))
  expect_error(covariates_options(end = "a"))
  expect_error(covariates_options(end = 1.5))
  expect_error(covariates_options(hind_step = NULL))
  expect_error(covariates_options(hind_step = "a"))
  expect_error(covariates_options(hind_step = c(1, 2)))
  expect_error(covariates_options(hind_step = 1.5))
  expect_error(covariates_options(min_lag = NULL))
  expect_error(covariates_options(min_lag = "a"))
  expect_error(covariates_options(min_lag = c(1, 2)))
  expect_error(covariates_options(min_lag = 1.5))
  expect_error(covariates_options(lead_time = NULL))
  expect_error(covariates_options(lead_time = "a"))
  expect_error(covariates_options(lead_time = c(1, 2)))
  expect_error(covariates_options(lead_time = 1.5))
  expect_error(covariates_options(fcast_nms = "a"))
  expect_error(covariates_options(fcast_nms = c(1, 2.5)))
  expect_error(covariates_options(fcast_nms = 1.5))
  expect_error(covariates_options(nfcnm = "a"))
  expect_error(covariates_options(nfcnm = c(1, 2)))
  expect_error(covariates_options(nfcnm = 1.5))
  expect_error(covariates_options(append_fcast_csv = 1))
  expect_error(covariates_options(append_fcast_csv = c(TRUE, TRUE)))
  expect_error(covariates_options(hist_fcast_file = 1))
  expect_error(covariates_options(hist_fcast_file = c("ok.csv", "ok.csv")))
  expect_error(covariates_options(source_name = 1))
  expect_error(covariates_options(source_name = c("ok", "ok")))
  expect_error(covariates_options(quiet = 1))
  expect_error(covariates_options(quiet = c(TRUE, FALSE)))
  expect_error(covariates_options(save = 1))
  expect_error(covariates_options(save = c(TRUE, FALSE)))
  expect_error(covariates_options(filename = 1))
  expect_error(covariates_options(tree = 1))
  expect_error(covariates_options(filename = c("ok.csv", "ok.csv")))
})

test_that("metadata_options", {
  expect_is(metadata_options(), "metadata_options")
  expect_error(metadata_options(quiet = 1))
  expect_error(metadata_options(quiet = c(TRUE, FALSE)))
  expect_error(metadata_options(cast_date = 1))
  expect_error(metadata_options(cast_date = c(today(), today())))
  expect_error(metadata_options(lead_time = NULL))
  expect_error(metadata_options(lead_time = "a"))
  expect_error(metadata_options(lead_time = c(1, 2)))
  expect_error(metadata_options(lead_time = 1.5))
  expect_error(metadata_options(cast_type = 1))
  expect_error(metadata_options(cast_type = c("forecasts", "forecasts")))
  expect_error(metadata_options(cast_type = "ok"))
  expect_error(metadata_options(confidence_level = "a"))
  expect_error(metadata_options(confidence_level = c(0.1, 0.2)))
  expect_error(metadata_options(confidence_level = 1.5))
  expect_error(metadata_options(confidence_level = -0.5))
  expect_error(metadata_options(save = 1))
  expect_error(metadata_options(save = c(TRUE, FALSE)))
  expect_error(metadata_options(filename = 1))
  expect_error(metadata_options(filename = c("ok.csv", "ok.csv")))
  expect_error(metadata_options(tree = 1))
  expect_error(metadata_options(covariate_source = 1))
  expect_error(metadata_options(covariate_source = "ok"))
  expect_error(metadata_options(covariate_source = rep("retroactive", 2)))
  expect_error(metadata_options(covariate_date_made = 1))
  expect_error(metadata_options(covariate_date_made = rep("ok", 2)))
})

test_that("predictions_options", {
  expect_is(predictions_options(), "predictions_options")
  expect_error(predictions_options(base = c("ok", "ok")))
  expect_error(predictions_options(main = c("ok", "ok")))
  expect_error(predictions_options(base = 1))
  expect_error(predictions_options(main = 1))
  expect_error(predictions_options(subs = 1))
  expect_error(predictions_options(quiet = 1))
  expect_error(predictions_options(quiet = c(TRUE, FALSE)))
  expect_error(predictions_options(download_existing_predictions = 1))
  expect_error(predictions_options(download_existing_predictions = 
                                c(TRUE, TRUE)))
})

test_that("models_options", {
  expect_is(models_options(), "models_options")
  expect_error(models_options(base = c("ok", "ok")))
  expect_error(models_options(main = c("ok", "ok")))
  expect_error(models_options(base = 1))
  expect_error(models_options(main = 1))
  expect_error(models_options(subs = 1))
  expect_error(models_options(quiet = 1))
  expect_error(models_options(quiet = c(TRUE, FALSE)))
  expect_is(models_options(model = "AutoArima"), "models_options")
  expect_silent(models_options(model = "AutoArima"))
})

test_that("cast_options", {
  expect_is(cast_options(), "cast_options")
  expect_error(cast_options(base = c("ok", "ok")))
  expect_error(cast_options(main = c("ok", "ok")))
  expect_error(cast_options(base = 1))
  expect_error(cast_options(main = 1))
  expect_error(cast_options(subs = 1))
  expect_error(cast_options(quiet = 1))
  expect_error(cast_options(quiet = c(TRUE, FALSE)))
  expect_is(cast_options(model = "AutoArima"), "cast_options")
  expect_silent(cast_options(model = "AutoArima"))
  expect_error(cast_options(cast_date = 1))
  expect_error(cast_options(cast_date = c(today(), today())))
  expect_error(cast_options(start = NULL))
  expect_error(cast_options(start = "a"))
  expect_error(cast_options(start = c(1, 2)))
  expect_error(cast_options(start = 1.5))
  expect_error(cast_options(end = "a"))
  expect_error(cast_options(end = 1.5))
  expect_error(cast_options(hind_step = NULL))
  expect_error(cast_options(hind_step = "a"))
  expect_error(cast_options(hind_step = c(1, 2)))
  expect_error(cast_options(hind_step = 1.5))
  expect_error(cast_options(min_plots = NULL))
  expect_error(cast_options(min_plots = "a"))
  expect_error(cast_options(min_plots = c(1, 2)))
  expect_error(cast_options(min_plots = 1.5))
  expect_error(cast_options(min_traps = NULL))
  expect_error(cast_options(min_traps = "a"))
  expect_error(cast_options(min_traps = c(1, 2)))
  expect_error(cast_options(min_traps = 1.5))
  expect_error(cast_options(ensemble = 1))
  expect_error(cast_options(ensemble = c(TRUE, TRUE)))
  expect_error(cast_options(cast_type = 1))
  expect_error(cast_options(cast_type = c("forecasts", "forecasts")))
  expect_error(cast_options(cast_type = "ok"))
})
