#' @title Create a models control list
#'
#' @description Creates a \code{list} of options for filling the models  
#'   subdirectory and writing the specific scripts. 
#'
#' @details Genetates a \code{list} of controls used in setting up the
#'   model scripts. Presently used elements are name, covariates and
#'   lag. Any model not in \code{\link{model_names}()} should be provided
#'   an entry, otherwise a name is autogenerated, and covariate is set
#'   to FALSE so lag = 0. \code{models_meta_prefab} is an available 
#'   data structure within the package that allows scaffolding, but input
#'   values override the existing values. 
#'
#' @param AutoArima,ESSS,nbGARCH,nbsGARCH,pevGARCH Control
#'   \code{lists} for each model, each containing \code{name}
#'   (\code{character} value of the model name),
#'   \code{covariates} (\code{logical} indicator of if the model needs
#'   covariates), \code{lag} (\code{integer}-conformable value of the
#'   lag to use with the covariates), and \code{update} (\code{logical}
#'   indicator of if the model script should be overwritten if it's present)
#'   elements.
#'
#' @param ... Additional \code{list}s or \code{model_control} \code{list}s
#'   defining control options for models to add to the prefab set. 
#'
#' @return \code{list} of models metadata, where each element is a model's
#'   list of model-creation variables (presently: name, covariates, lag, and
#'   update). The returned \code{list} will contain all models in the prefab 
#'   set and the models input via \code{control}.
#'
#' @examples
#'   models_control()
#'
#' @export
#'
models_control <- function(AutoArima = model_control("AutoArima"),
                           ESSS = model_control("ESSS"),
                           nbGARCH = model_control("nbGARCH"),
                           nbsGARCH = model_control("nbsGARCH"),
                           pevGARCH = model_control("pevGARCH", TRUE, 6), 
                           ...){
  out <- list(AutoArima = AutoArima, ESSS = ESSS, nbGARCH = nbGARCH,
              nbsGARCH = nbsGARCH, pevGARCH = pevGARCH)
  dots <- match.call(expand.dots = FALSE)$`...`
  ndots <- length(dots)
  dotsnames <- names(dots)
  if(ndots > 0){
    for(i in 1:ndots){
      if(is.null(dots[[i]]$name)){
        dots[[i]]$name <- dotsnames[i]
      }
      if(is.null(dots[[i]]$update)){
        dots[[i]]$update <- TRUE
      }
      out[[dotsnames[i]]] <- eval(dots[[i]])
    }
  }
  out
}

#' @title Create a model control list
#'
#' @description Creates a \code{list} of options for writing a specific model  
#'   script. 
#'
#' @param name \code{character} value of the model name.
#'
#' @param covariates \code{logical} indicator of if the model needs
#'   covariates. Defaults to \code{FALSE}.
#'
#' @param lag \code{integer}-conformable value of the lag to use with the
#'    covariates (defaults to \code{NA} as no covariates are used).
#'
#' @param update \code{logical} indicator of whether or not the predictions
#'   should be updated.
#'
#' @return \code{list} of model metadata (presently: name, covariates, lag
#'   and update).
#'
#' @examples
#'   models_control()
#'
#' @export
#'
model_control <- function(name = NULL, covariates = FALSE, lag = NA, 
                          update = TRUE){
  list(name = name, covariates = covariates, lag = lag, update = update)
}

#' @title Create a predictions control list
#'
#' @description Creates a \code{list} of options for filling the predictions  
#'   subdirectory, setting any non-set options to default values.
#'
#' @details Predictions can be downloaded from 
#'   \href{https://zenodo.org/record/3333770}{Zenodo} (default) or from the 
#'   \href{https://bit.ly/2Lo2xnQ}{portalPredictions repo}.
#'
#' @param download \code{logical} indicator for if the existing predictions 
#'   files should be retrieved.
#'
#' @param version \code{character} values of the version number or 
#'   \code{"latest"} (default) for the predictions to be download. 
#'   Versioning of the predictions on Zenodo is done by date.
#'
#' @param from_zenodo \code{logical} indicator of whether or not the 
#'   predictions should come from Zenodo (they will come from GitHub if not).
#'
#' @param update \code{logical} indicator of whether or not the predictions
#'   should be updated.
#'
#' @param use_existing_zip \code{logical} indicator of whether an existing
#'   zip in the temp directory should be used or overwritten when downloading 
#'   files.
#'
#' @param verbose \code{logical} indicator of whether or not to print out
#'   all of the details.
#'
#' @return A \code{list} of settings controlling the population of the
#'   PortalData subdirectory.
#'
#' @export
#'
predictions_control <- function(download = FALSE,
                                version = "latest", from_zenodo = TRUE,
                                update = TRUE, verbose = TRUE,
                                use_existing_zip = TRUE){
  list(download = download,
       version = version, from_zenodo = from_zenodo, update = update,
       verbose = verbose, use_existing_zip = use_existing_zip)
}

#' @title Create a PortalData control list
#'
#' @description Creates a \code{list} of options for filling the PortalData  
#'   subdirectory, setting any non-set options to default values.
#'
#' @param version \code{character} values of the version number or 
#'   \code{"latest"} (default) for the Portal Data to be download.
#'
#' @param from_zenodo \code{logical} indicator of whether or not the Portal 
#'   Data should come from Zenodo (come from GitHub if not).
#'
#' @param update \code{logical} indicator of whether or not the Portal Data
#'   should be updated.
#'
#' @return A \code{list} of settings controlling the population of the
#'   PortalData subdirectory.
#'
#' @export
#'
PortalData_control <- function(version = "latest", from_zenodo = TRUE,
                               update = TRUE){
  list(version = version, from_zenodo = from_zenodo, update = update)
}

#' @title Create data control lists
#'
#' @description Create the \code{list} of options controlling the filling of
#'   the data subdirectory, setting any non-set options 
#'   to default values. \cr \cr
#'   \code{data_control}: create a \code{list} of \code{list}s of 
#'   options for fully filling the data subdirectory. \cr \cr
#'   \code{moons_control}: create a \code{list} to control the making of
#'   the moons data. \cr \cr
#'   \code{rodents_control}: create a \code{list} to control the making of
#'   the rodents data. \cr \cr
#'   \code{covariates_control}: create a \code{list} to control the making of
#'   the covariates data. \cr \cr
#'   \code{metadata_control}: create a \code{list} to control the making of
#'   the metadata data. \cr \cr
#'
#' @param download \code{logical} indicator for if the existing covariate 
#'   predictions file should be retrieved.
#'
#' @param version \code{character} values of the version number or 
#'   \code{"latest"} (default) for the covariate predictions to be download. 
#'   Versioning of the predictions is done by date. 
#'
#' @param from_zenodo \code{logical} indicator of whether or not the 
#'   covariate predictions should come from Zenodo (they will come from GitHub
#'   if not, unless \code{download = FALSE}, in which case they will come
#'   from the data within the package).
#'
#' @param update \code{logical} indicator of whether or not the data sets
#'   should be updated.
#'
#' @param cast_date \code{Date} from which future is defined, typically 
#'   today's date (set using \code{\link{today}}).
#'
#' @param append_missing_to_raw \code{logical} indicator dictating if the 
#'   missing moon dates should be appended to the raw data file (should be 
#'   \code{TRUE} to allow the imported portalr functions to work properly).
#'
#' @param m_save \code{logical} indicator controlling if the moons data should 
#'   be saved out.
#'
#' @param m_filename \code{character} name of the file for saving moons data.
#'
#' @param tmnt_type Treatment type: \code{"all"} or \code{"controls"}.
#'
#' @param start \code{integer} (or integer \code{numeric}) newmoon number of 
#'   the first sample to be included. Default value is \code{217}, 
#'   corresponding to \code{1995-01-01}.
#'
#' @param end \code{integer} (or integer \code{numeric}) newmoon number of the
#'   last sample to be included. Default value is \code{NULL}, which equates
#'   to the most recently included sample. If \code{cast_type} is 
#'   \code{"hindcasts"} and \code{end} is \code{NULL}, default becomes 
#'   \code{490:403}, corresponding to \code{2017-01-01} back to
#'   \code{2010-01-01}.
#'
#' @param hind_step \code{integer} (or integer \code{numeric}) iteration 
#'   parameter used to work across the input values for \code{end}. Default is
#'   \code{1}, which is likely all it should be run using.
#'
#' @param drop_spp \code{character}-valued vector of species names to drop 
#'   from the forecasting.
#'
#' @param min_traps \code{integer} (or integer \code{numeric}) of the minimum 
#'   number of traps collected for a plot to be used.
#'
#' @param min_plots \code{integer} (or integer \code{numeric}) of the minimum 
#'   number of plots surveyed for a survey to be used.
#'
#' @param level \code{character} input for 
#'   \code{\link[portalr]{summarize_rodent_data}}, automatically set by 
#'   \code{tmnt_type}.
#'
#' @param treatment \code{character} input for 
#'   \code{\link[portalr]{summarize_rodent_data}}, automatically set by 
#'   \code{tmnt_type}.
#'
#' @param plots \code{character} input for 
#'   \code{\link[portalr]{summarize_rodent_data}}, automatically set by 
#'   \code{tmnt_type}.
#'
#' @param output \code{character} input for 
#'   \code{\link[portalr]{summarize_rodent_data}}, automatically set by 
#'   \code{tmnt_type}.
#'
#' @param r_save \code{logical} value indicating if the rodent data should be 
#'   saved out.
#'
#' @param r_filename \code{character} name of the file to save the rodent data
#'   in.
#'
#' @param cov_hist \code{logical} indicator of whether or not historical 
#'   covariates are to be included.
#'
#' @param cov_fcast \code{logical} indicator whether or not forecasted 
#'   covariates are to be included.
#'
#' @param yr \code{numeric} value of the year of today's date.
#'
#' @param lead_time \code{integer} (or integer \code{numeric}) number of moons
#'   into the future the rodents are to be forecast.
#'
#' @param min_lag \code{integer} (or integer \code{numeric}) of the minimum 
#'   covariate lag time used in any model.
#'
#' @param fcast_nms \code{integer} (or integer \code{numeric}) vector of 
#'   newmoon numbers to be forecast for covariates.
#'
#' @param nfcnm \code{integer} (or integer \code{numeric}) number of forecast 
#'   newmoons for covariates.
#'
#' @param append_fcast_csv \code{logical} indicator controlling if the new 
#'   forecast should be appended to the historical forecasts for the purposes 
#'   of hindcasting.
#'
#' @param hist_fcast_file \code{character} name of the file where the 
#'   historical covariate forecasts are held.
#'
#' @param source_name \code{character} value for the name to give the 
#'   covariate forecast. Currently is \code{"current_archive"}. Previous to
#'   \code{"current_archive"}, the data were retroactively filled in and are 
#'   given the source name \code{"retroactive"}.
#'
#' @param c_save \code{logical} indicator for if the covariate data should be 
#'   saved out.
#'
#' @param c_filename \code{character} value for the name of the covariate file 
#'   for the saving if \code{c_save} is \code{TRUE}.
#'
#' @param cast_type -cast type: \code{"forecasts"} or \code{"hindcasts"}.
#'
#' @param confidence_level \code{numeric} confidence level used in 
#'   summarizing model output. Must be between \code{0} and \code{1}.
#'
#' @param meta_save \code{logical} indicator for if the metadata should be
#'   saved out
#'
#' @param meta_filename \code{character} value for the name of the metadata 
#'   file for the saving if \code{meta_save} is \code{TRUE}.
#'
#' @param covariate_source \code{character} value for the name tagged to the
#'   covariate forecast. Possible values include \code{"current_archive"} and
#'   \code{"retroactive"} for hindcasts. Not presently needed for 
#'   implementation in forecasts.
#'
#' @param covariate_date_made \code{character} value for the date-time tagged 
#'   to the covariate forecast. Possible values depend on the dates available 
#'   for covariates saved in the covariate_forecasts file for hindcasts. Not 
#'   presently needed for implementation in forecasts.
#'
#' @param override_ssl_cert_exp \code{logical} indicator for if the error
#'   caused by the expiration of the SSL certificate should be overriden.
#'
#' @param verbose \code{logical} indicator of whether or not to print out
#'   all of the details.
#'
#' @param use_existing_zip \code{logical} indicator of whether an existing
#'   zip in the temp directory should be used or overwritten when downloading 
#'   files.
#'
#' @param n_future_moons \code{integer} (or integer \code{numeric}) value for 
#'   the number of future moons to add.
#'
#' @param save General \code{logical} indicator for if the file should be
#'   saved out.
#'
#' @param filename General \code{character} value for the name of the 
#'   file for the saving if \code{save} is \code{TRUE}.
#'
#' @param class General \code{character} value for the name of the 
#'   special class of the data object.
#'
#' @param rodents A \code{list} of arguments to control creating the
#'   rodents data files. See \code{\link{rodents_control}}.
#'
#' @param covariates A \code{list} of arguments to control creating the
#'   covariates data files. See \code{\link{covariates_control}}.
#'
#' @param moons A \code{list} of arguments to control creating the
#'   moons data files. See \code{\link{moons_control}}.
#'
#' @param metadata A \code{list} of arguments to control creating the
#'   metadata data files. See \code{\link{metadata_control}}.
#'
#' @return \code{data_control}: a \code{list} of control 
#'   options \code{list}s (\code{moons} generated by \code{moons_control}, 
#'   \code{rodents} generated by \code{rodents_control}, \code{covariates},
#'   generated by \code{covariates_control}, and \code{metadata} generated by
#'   \code{metadata_control}. \cr \cr
#'   \code{moons_control}: a \code{list} of settings controlling the moons
#'   data creation. \cr \cr
#'   \code{rodents_control}: a \code{list} of settings controlling the 
#'   rodents data creation. \cr \cr
#'   \code{covariates_control}: a \code{list} of settings controlling the
#'   covariates data creation. \cr \cr
#'   \code{metadata_control}: a \code{list} of settings controlling the
#'   metadata creation. \cr \cr
#'
#' @export
#'
data_control <- function(moons = moons_control(),
                         rodents = rodents_control(),
                         covariates = covariates_control(),
                         metadata = metadata_control()){

  list(moons = moons, rodents = rodents, covariates = covariates,
       metadata = metadata)
}

#' @rdname data_control
#'
#' @export
#'
moons_control <- function(n_future_moons = 12, cast_date = today(), 
                          append_missing_to_raw = TRUE, m_save = TRUE,
                          m_filename = "moons.csv", class = "moons",
                          update = TRUE){
  list(n_future_moons = n_future_moons, cast_date = cast_date, 
       append_missing_to_raw = append_missing_to_raw, m_save = m_save,
       m_filename = m_filename, update = update, class = class)
}

#' @rdname data_control
#'
#' @export
#'
covariates_control <- function(cast_type = "forecasts", cov_hist = TRUE, 
                               cov_fcast = TRUE, cast_date = today(), 
                               yr = as.numeric(format(today(), "%Y")),
                               start = 217, end = NULL, hind_step = 1, 
                               lead_time = 12, min_lag = 6, fcast_nms = NULL,
                               nfcnm = 0, append_fcast_csv = TRUE, 
                               hist_fcast_file = "covariate_forecasts.csv",
                               source_name = "current_archive",
                               c_save = TRUE, c_filename = "covariates.csv",
                               class = "covariates",
                               override_ssl_cert_exp = TRUE,
                               download = FALSE, version = "latest",
                               from_zenodo = TRUE, verbose = FALSE,
                               update = TRUE,
                               use_existing_zip = TRUE){
  if (is.null(end) & cast_type == "hindcasts"){
    end <- 490:403
  }
  list(cast_type = cast_type, cov_hist = cov_hist, cov_fcast = cov_fcast, 
       cast_date = cast_date, yr = yr, start = start, end = end, 
       hind_step = hind_step, lead_time = lead_time, min_lag = min_lag, 
       fcast_nms = fcast_nms, nfcnm = nfcnm, 
       append_fcast_csv = append_fcast_csv, hist_fcast_file = hist_fcast_file,
       source_name = source_name, c_save = c_save, c_filename = c_filename, 
       class = class, override_ssl_cert_exp = override_ssl_cert_exp,
       download = download, version = version, from_zenodo = from_zenodo,
       verbose = verbose, update = update,
       use_existing_zip = use_existing_zip)
}

#' @rdname data_control
#'
#' @export
#'
rodents_control <- function(cast_type = "forecasts",
                            start = 217, end = NULL, hind_step = 1, 
                            drop_spp = "PI", min_plots = 24, level = "Site", 
                            treatment = NULL, plots = "all", min_traps = 1,
                            output = "abundance", r_save = TRUE, 
                            r_filename = "all.csv", 
                            update = TRUE, class = "rodents"){
  if (is.null(end) & cast_type == "hindcasts"){
    end <- 490:403
  }
  list(cast_type = cast_type, start = start, end = end, min_traps = min_traps,
       hind_step = hind_step, drop_spp = drop_spp, min_plots = min_plots, 
       level = level, plots = plots, output = output, r_save = r_save, 
       r_filename = r_filename, treatment = treatment, 
       update = update, class = class)
}

#' @rdname data_control
#'
#' @export
#'
metadata_control <- function(cast_date = today(), cast_type = "forecasts",
                             confidence_level = 0.9, lead_time = 12,
                             meta_save = TRUE, 
                             meta_filename = "metadata.yaml", 
                             covariate_source = "retroactive",
                             covariate_date_made = "2018-06-05 12:00:00 PST",
                             class = "metadata", update = TRUE){
  list(cast_date = cast_date, cast_type = cast_type, 
       confidence_level = confidence_level,lead_time = lead_time, 
       meta_save = meta_save, meta_filename = meta_filename, 
       update = update, class = class)
}
