#' @title Prepare options for a portalcasting directory
#'
#' @description Suite of functions used to generate options lists: \cr \cr
#'  \code{all_options} creates the full hierarchy of lists
#'
#' @param base name of the base directory where the forecasting 
#'   directory should exist (will be created if it doesn't)
#'
#' @param main name of the portalcasting directory
#'
#' @param subs names of the portalcasting subdirectories
#'
#' @param quiet logical indicator if progress messages should be quieted
#'
#' @param fdate date from which future is defined, typically today's date.
#'
#' @param append_missing_to_raw logical indicating if the missing moon dates 
#'   should be appended to the raw data file (should be TRUE to allow the
#'   imported portalr functions to work properly)
#'
#' @param m_save logical if the moons data should be saved out
#'
#' @param m_filename the name of the file for saving moons data
#'
#' @param tmnt_type "all" or "controls"
#'
#' @param start newmoon number of the first sample to be included. Default 
#'   value is \code{217}, corresponding to 1995-01-01
#'
#' @param end newmoon number of the last sample to be included. Default
#'   value is \code{NULL}, which equates to the most recently included
#'   sample. If \code{cast_type} is "hindcasts" and \code{end} is \code{NULL},
#'   default becomes \code{490:403}, corresponding to 2017-01-01 back to
#'   2010-01-01
#'
#' @param hind_step an iteration parameter to work across the input values 
#'   for \code{end}. Default is 1, which is likely all it should be run using
#'
#' @param drop_spp species names to drop from the table
#'
#' @param min_plots minimum number of plots surveyed for a survey to be used
#'
#' @param min_traps minimum number of traps trapped for a plot to be used
#'
#' @param level for get_rodent_data, automatically set by tmnt_type
#'
#' @param treatment for get_rodent_data, automatically set by tmnt_type
#'
#' @param plots for get_rodent_data, automatically set by tmnt_type
#'
#' @param output for get_rodent_data, automatically set by tmnt_type
#'
#' @param r_save logical if the data should be saved out
#'
#' @param r_filename the name of the file to save the rodent data in
#'
#' @param cov_hist logical indicator whether or not historical covariates are
#'   to be included
#'
#' @param cov_fcast logical indicator whether or not forecasted covariates are
#'   to be included
#'
#' @param yr year of today
#'
#' @param lead_time number of moons into the future the rodents are forecast
#'
#' @param min_lag the minimum lag time used in any model
#'
#' @param fcast_nms newmoon numbers to be forecast for covariates
#'
#' @param nfcnm number of forecast newmoons for covariates
#'
#' @param append_fcast_csv logical if the new forecast should be appended to
#'   the historical forecasts for the purposes of hindcasting
#'
#' @param hist_fcast_file name of the file where the historical 
#'   covariate forecasts are held
#'
#' @param source_name character value for the name to give the covariaate
#'   forecast. Currently is "current_archive". Previous to "current_archive",
#'   the data were retroactively filled in and are given the source name
#'   "retroactive"
#'
#' @param c_save logical if the covariate data should be saved out
#'
#' @param c_filename the name of the covariate file for the saving
#'
#' @param cast_type "forecasts" or "hindcasts" 
#'
#' @param confidence_level confidence level used in summarizing model output
#'
#' @param meta_save logical if the metadata should be saved out
#'
#' @param meta_filename the name of the metadata file for the saving
#'
#' @param download_existing_predictions logical indicator is the existing
#'   predictions files should be retrieved from the portalPredictions repo
#'
#' @param model names of model scripts to include
#'
#' @param ensemble logical indicator of whether to create an ensemble model
#'
#' @param version version number or "latest" (default) for the Portal Data
#'   download
#'
#' @param from_zenodo logical indicator of whether or not the Portal Data 
#'   should come from Zenodo (come from GitHub if not)
#'
#' @return \code{all_options}: list of control options lists ("options_dir"
#'   generated by \code{dir_options}, "options_PortalData" generated by 
#'   \code{PortalData_options}, "options_data" generated by 
#'   \code{data_options}, "options_predictions" generated by
#'   \code{predictions_options}, "options_models" generated by
#'   \code{models_options}, and "options_cast" generated by 
#'   \code{cast_options}.
#'
#' @export
#'
all_options <- function(base = ".", main = "", subs = subdirs(), 
                        quiet = FALSE, fdate = today(), 
                        append_missing_to_raw = TRUE, m_save = TRUE, 
                        m_filename = "moons.csv", tmnt_type = NULL,
                        start = 217, end = NULL, hind_step = 1, 
                        drop_spp = "PI", min_plots = 24, min_traps = 1,
                        level = "Site", treatment = NULL, plots = "all",
                        output = "abundance", r_save = TRUE, 
                        r_filename = "all.csv",
                        cov_hist = TRUE, cov_fcast = TRUE, 
                        yr = as.numeric(format(today(), "%Y")),
                        lead_time = 12, min_lag = 6, 
                        fcast_nms = NULL, nfcnm = 0,
                        append_fcast_csv = TRUE, 
                        hist_fcast_file = "covariate_forecasts.csv",
                        source_name = "current_archive",
                        c_save = TRUE, c_filename = "covariates.csv",
                        cast_type = "forecasts",
                        confidence_level = 0.9, meta_save = TRUE, 
                        meta_filename = "metadata.yaml",
                        download_existing_predictions = FALSE,
                        model = models(), ensemble = TRUE,
                        version = "latest", from_zenodo = TRUE){

  if (is.null(end) & cast_type == "hindcasts"){
    end <- 490:403
  }
  list(
    options_dir = dir_options(base = base, main = main, subs = subs,
                              quiet = quiet),
    options_PortalData = PortalData_options(base = base, main = main, 
                                            subs = subs, quiet = quiet,
                                            version = version, 
                                            from_zenodo = from_zenodo),
    options_data = data_options(base = base, main = main, subs = subs,
                                quiet = quiet, fdate = fdate,
                                append_missing_to_raw = append_missing_to_raw,
                                m_save = m_save, m_filename = m_filename,
                                tmnt_type = tmnt_type, start = start, 
                                end = end, hind_step = hind_step,
                                drop_spp = drop_spp, min_plots = min_plots, 
                                level = level, treatment = treatment, 
                                plots = plots, output = output,
                                r_save = r_save, r_filename = r_filename,
                                cov_hist = cov_hist, 
                                cov_fcast = cov_fcast, yr = yr, 
                                lead_time = lead_time, min_lag = min_lag, 
                                fcast_nms = fcast_nms, nfcnm = nfcnm,
                                append_fcast_csv = append_fcast_csv, 
                                hist_fcast_file = hist_fcast_file,
                                source_name = source_name,
                                c_save = c_save, c_filename = c_filename,
                                cast_type = cast_type,
                                confidence_level = confidence_level,  
                                meta_save = meta_save, 
                                meta_filename = meta_filename),
    options_predictions = predictions_options(base = base, main = main, 
                                              subs = subs,
                                              download_existing_predictions = 
                                                download_existing_predictions, 
                                              quiet = quiet),
    options_models = models_options(base = base, main = main, subs = subs,
                                    quiet = quiet, model = model),
    options_cast = cast_options(base = base, main = main, subs = subs, 
                                quiet = quiet, model = model, 
                                cast_type = cast_type, 
                                fdate = fdate, ensemble = ensemble,
                                start = start, end = end, 
                                hind_step = hind_step, 
                                min_plots = min_plots, min_traps = min_traps)
  )

}

#' @rdname all_options
#'
#' @description \code{dir_options} creates a list of control options for the
#'   directory set-up
#'
#' @return \code{dir_options}: a list of settings controlling the directory
#'   structure creation
#'
#' @export
#'
dir_options <- function(base = ".", main = "", subs = subdirs(),
                        quiet = FALSE){
  tree <- dirtree(base, main, subs)
  list(tree = tree, quiet = quiet)
}

#' @rdname all_options
#'
#' @description \code{PortalData_options} creates a list of options for
#'   filling the PortalData subdirectory
#'
#' @return \code{PortalData_options}: a list of settings controlling the 
#'   creation and population of the PortalData subdirectory
#'
#' @export
#'
PortalData_options <- function(base = ".", main = "", subs = subdirs(), 
                               quiet = FALSE,
                               version = "latest", from_zenodo = TRUE){

  tree <- dirtree(base, main, subs)
  list(tree = tree, version = version, from_zenodo = from_zenodo, 
       quiet = quiet)
}


#' @rdname all_options
#'
#' @description \code{data_options} creates a list of lists of options for
#'   filling the data subdirectory
#'
#' @return \code{data_options}: list of control options lists ("moons"
#'   generated by \code{moons_options}, "rodents" generated by 
#'   \code{rodents_options}, "covariates" generated by
#'   \code{covariates_options}, and "metadata" generated by
#'   \code{metadata_options}, as well as items "cast_type", "tree",  and
#'   "quiet" for simple use with all or ancillary data.
#'
#' @export
#'
data_options <- function(base = ".", main = "", subs = subdirs(),
                         quiet = FALSE, fdate = today(), 
                         append_missing_to_raw = TRUE, m_save = TRUE, 
                         m_filename = "moons.csv", tmnt_type = NULL, 
                         start = 217, end = NULL, hind_step = 1, 
                         drop_spp = "PI", min_plots = 24, 
                         level = "Site", treatment = NULL, plots = "all",
                         output = "abundance", r_save = TRUE, 
                         r_filename = "all.csv",
                         cov_hist = TRUE, cov_fcast = TRUE, 
                         yr = as.numeric(format(today(), "%Y")),
                         lead_time = 12, min_lag = 6, 
                         fcast_nms = NULL, nfcnm = 0,
                         append_fcast_csv = TRUE, 
                         hist_fcast_file = "covariate_forecasts.csv",
                         source_name = "current_archive",
                         c_save = TRUE, c_filename = "covariates.csv",
                         cast_type = "forecasts",
                         confidence_level = 0.9, 
                         meta_save = TRUE, meta_filename = "metadata.yaml"){

  if (is.null(end) & cast_type == "hindcasts"){
    end <- 490:403
  }
  tree <- dirtree(base, main, subs)
  list(
    moons = moons_options(n_future_moons = lead_time, fdate = fdate,
                          append_missing_to_raw = append_missing_to_raw,
                          save = m_save, filename = m_filename,
                          quiet = quiet, tree = tree),
    rodents = rodents_options(cast_type = cast_type,
                              tmnt_type = tmnt_type, start = start, end = end,
                              hind_step = hind_step, 
                              drop_spp = drop_spp, min_plots = min_plots, 
                              level = level, treatment = treatment, 
                              plots = plots, output = output,
                              save = r_save, filename = r_filename,
                              quiet = quiet, tree = tree),
    covariates = covariates_options(cast_type = cast_type, 
                                    cov_hist = cov_hist, 
                                    cov_fcast = cov_fcast, fdate = fdate, 
                                    yr = yr, start = start, end = end, 
                                    hind_step = hind_step, 
                                    lead_time = lead_time, min_lag = min_lag, 
                                    fcast_nms = fcast_nms, nfcnm = nfcnm,
                                    append_fcast_csv = append_fcast_csv, 
                                    hist_fcast_file = hist_fcast_file,
                                    source_name = source_name,
                                    save = c_save, filename = c_filename,
                                    quiet = quiet, tree = tree),
    metadata = metadata_options(fdate = fdate, 
                                cast_type = cast_type,
                                confidence_level = confidence_level,
                                lead_time = lead_time, save = meta_save,
                                filename = meta_filename, quiet = quiet, 
                                tree = tree),
    cast_type = cast_type, quiet = quiet, tree = tree   
  )
}

#' @rdname all_options
#'
#' @description \code{moons_options} creates a list of options for the moons
#'   data
#'
#' @param n_future_moons integer value for the number of future moons to add
#'
#' @param save logical if the specific data should be saved out
#'
#' @param filename the name of the file for the saving
#'
#' @param tree directory tree
#'
#' @return \code{moons_options}: a list of settings controlling the moon data
#'   creation
#'
#' @export
#'
moons_options <- function(n_future_moons = 12, fdate = today(), 
                          append_missing_to_raw = TRUE, save = TRUE,
                          filename = "moons.csv", tree = dirtree(), 
                          quiet = FALSE){
  list(n_future_moons = n_future_moons, fdate = fdate, 
       append_missing_to_raw = append_missing_to_raw, save = save,
       filename = filename, tree = tree, quiet = quiet)
}

#' @rdname all_options
#'
#' @description \code{rodents_options} creates a list of options for the 
#'   rodents data
#'
#' @return \code{rodents_options}: a list of settings controlling the rodents
#'   data creation
#'
#' @export
#'
rodents_options <- function(cast_type = "forecasts", tmnt_type = NULL, 
                            start = 217, end = NULL, hind_step = 1, 
                            drop_spp = "PI", min_plots = 24, level = "Site", 
                            treatment = NULL, plots = "all",
                            output = "abundance", save = TRUE, 
                            filename = "all.csv", tree = dirtree(), 
                            quiet = FALSE){
  if (!is.null(tmnt_type)){
    if (tmnt_type == "all"){
      level <- "Site"
      plots <- "all"
      output <- "abundance"
      filename <- "all.csv"
    }
    if (tmnt_type == "controls"){
      level <- "Treatment"
      plots <- "Longterm"
      output <- "abundance"
      treatment <- "control"
      filename <- "controls.csv"
    }  
  }
  list(cast_type = cast_type, start = start, end = end, hind_step = hind_step,
       drop_spp = drop_spp, min_plots = min_plots, 
       tmnt_type = tmnt_type, level = level, plots = plots, output = output,
       save = save, filename = filename, treatment = treatment, tree = tree,
       quiet = quiet)
}

#' @rdname all_options
#'
#' @description \code{covariates_options} creates a list of options for the 
#'   covariates data
#'
#' @return \code{covariates_options}: a list of settings controlling the 
#'   covariates data creation
#'
#' @export
#'
covariates_options <- function(cast_type = "forecasts", cov_hist = TRUE, 
                               cov_fcast = TRUE, fdate = today(), 
                               yr = as.numeric(format(today(), "%Y")),
                               start = 217, end = NULL, hind_step = 1, 
                               lead_time = 12, min_lag = 6, fcast_nms = NULL,
                               nfcnm = 0, append_fcast_csv = TRUE, 
                               hist_fcast_file = "covariate_forecasts.csv",
                               source_name = "current_archive",
                               save = TRUE, filename = "covariates.csv", 
                               tree = dirtree(), quiet = FALSE){
  if (is.null(end) & cast_type == "hindcasts"){
    end <- 490:403
  }
  list(cast_type = cast_type, cov_hist = cov_hist, cov_fcast = cov_fcast, 
       fdate = fdate, yr = yr, start = start, end = end, 
       hind_step = hind_step, lead_time = lead_time, min_lag = min_lag, 
       fcast_nms = fcast_nms, nfcnm = nfcnm, 
       append_fcast_csv = append_fcast_csv, hist_fcast_file = hist_fcast_file,
       source_name = source_name, save = save, filename = filename, 
       tree = tree, quiet = quiet)
}

#' @rdname all_options
#'
#' @description \code{metadata_options} creates a list of options for the 
#'   metadata creation
#'
#' @return \code{metadata_options}: a list of settings controlling the 
#'   metadata creation
#'
#' @export
#'
metadata_options <- function(fdate = today(), cast_type = "forecasts",
                             confidence_level = 0.9, lead_time = 12,
                             save = TRUE, filename = "metadata.yaml", 
                             quiet = FALSE, tree = dirtree()){

  list(fdate = fdate, cast_type = cast_type, 
       confidence_level = confidence_level,lead_time = lead_time, save = save,
       filename = filename, quiet = quiet, tree = tree)
}

#' @rdname all_options
#'
#' @description \code{predictions_options} creates a list of options for 
#'   populating the predictions subdirectory
#'
#' @return \code{predictions_options}: a list of settings controlling the 
#'   population of the predictions subdirectory
#'
#' @export
#'
predictions_options <- function(base = ".", main = "", 
                                subs = subdirs(), 
                                download_existing_predictions = FALSE,
                                quiet = FALSE){
  tree <- dirtree(base, main, subs)
  list(tree = tree, 
       download_existing_predictions = download_existing_predictions, 
       quiet = quiet)
}

#' @rdname all_options
#'
#' @description \code{models_options} creates a list of options for 
#'   populating the models subdirectory
#'
#' @return \code{models_options}: a list of settings controlling the 
#'   population of the models subdirectory
#'
#' @export
#'
models_options <- function(base = ".", main = "", subs = subdirs(),
                           quiet = FALSE, model = models()){

  tree <- dirtree(base, main, subs)
  list(model = model, quiet = quiet, tree = tree)
}

#' @rdname all_options
#'
#' @description \code{cast_options} creates a list of control options for 
#'   running \code{\link{portalcast}}
#'
#' @return \code{cast_options}: a list of settings controlling the running of
#'   \code{\link{portalcast}}
#'
#' @export
#'
cast_options <- function(base = ".", main = "", subs = subdirs(), 
                         quiet = FALSE, model = models(), 
                         cast_type = "forecasts", fdate = today(), 
                         ensemble = TRUE, start = 217, end = NULL, 
                         hind_step = 1, min_plots = 24, min_traps = 1){
  tree <- dirtree(base, main, subs)
  list(tree = tree, quiet = quiet, model = model, cast_type = cast_type,
       fdate = fdate, ensemble = ensemble, start = start, end = end, 
       hind_step = hind_step, min_plots = min_plots, min_traps = min_traps)
}