#' @title Prepare model metadata
#'
#' @description Set up the metadata list used for -casting, primarily the 
#'   time periods.
#'
#' @param moons Class-\code{moons} \code{data.frame} containing the historic 
#'   and future newmoons, as produced by \code{\link{prep_moons}}. 
#'
#' @param rodents_list A class-\code{rodents_list} \code{list} of two class-
#'   \code{rodents} \code{data.frame}s, \code{all} (abundances on all plots)
#'   and \code{controls} (abundances on control plots only).
#'
#' @param covariates Covariate data table as a code{covariates}-class 
#'   \code{data.frame} generated by \code{\link{prep_covariates}}
#'
#' @param tree \code{dirtree}-class directory tree list. See 
#'   \code{\link{dirtree}}.
#'
#' @param quiet \code{logical} indicator controlling if messages are printed.
#'
#' @param control \code{list} of parameters to control the preparation of 
#'   metadata. See \code{\link{metadata_control}}.
#'
#' @return Model metadata as a \code{metadata}-class \code{list}.
#' 
#' @examples
#' \dontrun{
#' 
#' setup_dir()
#' prep_metadata()
#' }
#'
#' @export
#'
prep_metadata <- function(moons = prep_moons(), 
                          rodents_list = prep_rodents_list(), 
                          covariates = prep_covariates(), 
                          tree = dirtree(), quiet = FALSE, control = list()){
  
  control <- do.call("metadata_control", control)
  messageq("Loading metadata file into data subdirectory", quiet)
  forecast_date <- control$cast_date
  
  covariates_fcasts <- which(covariates$source == "fcast")
  if (control$cast_type == "forecasts"){
    which_last_newmoon <- max(which(moons$newmoondate < forecast_date))
    last_newmoon <- moons$newmoonnumber[which_last_newmoon]
  }
  if (control$cast_type == "hindcasts"){
    last_newmoon <- max(covariates$newmoonnumber[covariates$source == "hist"]) 
  }
  last_rodent_pd_all <- tail(rodents_list$all, 1)$period
  last_rodent_pd_control <- tail(rodents_list$control, 1)$period
  last_rodent_pd <- max(last_rodent_pd_all, last_rodent_pd_control)
  which_last_rodent_pd <- which(moons$period == last_rodent_pd)
  last_rodent_newmoon <- moons$newmoonnumber[which_last_rodent_pd]
  last_covar_newmoon <- tail(covariates, 1)$newmoonnumber

  first_fcast_covar_newmoon <- last_covar_newmoon + 1
  first_fcast_rodent_newmoon <- last_rodent_newmoon + 1
  last_fcast_newmoon <- last_newmoon + control$lead_time

  rodent_fcast_newmoons <- first_fcast_rodent_newmoon:last_fcast_newmoon
  which_r_nms <- which(moons$newmoonnumber %in% rodent_fcast_newmoons)
  rodent_nm_dates <- moons$newmoondate[which_r_nms]
  rodent_fcast_months <- as.numeric(format(rodent_nm_dates, "%m"))
  rodent_fcast_years <- as.numeric(format(rodent_nm_dates, "%Y"))

  covar_fcast_newmoons <- first_fcast_covar_newmoon:last_fcast_newmoon
  which_c_nms <- which(moons$newmoonnumber %in% covar_fcast_newmoons)
  covar_nm_dates <- moons$newmoondate[which_c_nms]
  covar_fcast_months <- as.numeric(format(covar_nm_dates, "%m"))
  covar_fcast_years <- as.numeric(format(covar_nm_dates, "%Y"))

  out <-  list(cast_type = control$cast_type, 
               forecast_date = as.character(forecast_date), 
               covariate_forecast_newmoons = covar_fcast_newmoons, 
               covariate_forecast_months = covar_fcast_months, 
               covariate_forecast_years = covar_fcast_years,
               rodent_forecast_newmoons = rodent_fcast_newmoons, 
               rodent_forecast_months = rodent_fcast_months, 
               rodent_forecast_years = rodent_fcast_years,
               confidence_level = control$confidence_level,
               covariate_source = control$covariate_source,
               covariate_date_made = control$covariate_date_made)
  if (control$save){
    local_path <- paste0("data/", control$filename)
    con_path <- file_paths(tree, local_path)
    writeLines(as.yaml(out), con = con_path)
  }
  classy(out, c(class(out), "metadata"))
}