#' @title Prepare temporal (lunar) data
#'
#' @description A set of functions that get time information (calendar dates, 
#'   census periods, and newmoon numbers) associated with trapping events 
#'   (achieved and missed) based on a lunar survey schedule. If needed, 
#'   additional moons will be added to both the in-use and raw versions of 
#'   the data table. \cr \cr
#'   \code{append_past_moons_to_raw} Appends missing past moon dates to the
#'   raw data. \cr \cr
#'   \code{add_future_moons} Adds future moon dates to the moon table. \cr \cr
#'   \code{add_addl_future_moons} Add more more moons to accomplish requested 
#'    forecast length. \cr \cr
#'
#' @details \code{append_past_moons_to_raw}:
#'   Sometimes the raw moon data table is not up-to-date. Because
#'   the \code{portalr} functions \code{\link[portalr]{weather}} and 
#'   \code{\link[portalr]{fcast_ndvi}} point to the raw moons data, that table
#'   needs to be updated to produce the correct current data table for 
#'   casting. \cr \cr
#'   \code{add_future_moons}:
#'   Add future moons to the moon table, counting forward from
#'   the forecast date (\code{options_moons$cast_date}). Because the 
#'   \code{moons} table might not have the most recent moons, more rows than 
#'   anticipated (\code{options_moons$n_future_moons}) may need to be added to 
#'   the table. \cr \cr
#'   \code{add_addl_future_moons}: 
#'   Add extra future moons to the moon table to achieve requested
#'   forecast length. Because the moon table might not have the most recent 
#'   moons, more rows than initially requested may need to be added to the 
#'   table for it to be of the required coverage.
#'
#' @param tree \code{dirtree}-class directory tree list. See 
#'   \code{\link{dirtree}}.
#'
#' @param quiet \code{logical} indicator controlling if messages are printed.
#'
#' @param control \code{list} of parameters to control the preparation of 
#'   moons. See \code{\link{moons_control}}.
#'
#' @param moons Moons data table as a code{moons}-class \code{data.frame}.
#'
#' @param future_moons A \code{moons}-class \code{data.frame} forward from 
#'   the historic moons table (produced by \code{\link{prep_moons}}), as
#'   generated by \code{\link[portalr]{get_future_moons}}.  
#'
#' @return 
#'  \code{prep_moons}: Fully appended \code{moons}data table as a 
#'    code{moons}-class \code{data.frame}.
#'  \code{append_past_moons_to_raw}, \code{add_future_moons}, 
#'    \code{add_addl_future_moons}: Appropropriately appended \code{moons} 
#'    data table as a \code{moons}-class \code{data.frame}.
#'   
#' @examples
#' \dontrun{
#' 
#' setup_dir()
#' prep_moons()
#' }
#'
#' @export
#' 
prep_moons <- function(tree = dirtree(), quiet = FALSE,
                       control = list()){
  control <- do.call("moons_control", control)
  messageq("Loading moons data file into the data subdirectory", quiet)
  verify_PortalData(tree, quiet = quiet)
  file_paths(tree, "PortalData/Rodents/moon_dates.csv") %>%
  read.csv(stringsAsFactors = FALSE) %>% 
  classy(c("data.frame", "moons")) %>%
  add_future_moons(control) %>%
  append_past_moons_to_raw(tree, control) %>%
  format_moons() %>%
  dataout(tree, control)
}

#' @rdname prep_moons
#'
#' @export
#'
append_past_moons_to_raw <- function(moons, tree = dirtree(), 
                                     control = list()){
  control <- do.call("moons_control", control)
  if (control$append_missing_to_raw){
    pth <- file_paths(tree, "PortalData/Rodents/moon_dates.csv")
    included_moons <- moons$newmoondate < today()
    newraw <- moons[included_moons, ]
    write.csv(newraw, pth, row.names = FALSE)
  }
  moons
}

#' @rdname prep_moons
#'
#' @export
#' 
add_future_moons <- function(moons = prep_moons(), control = list()){
  control <- do.call("moons_control", control)
  if (control$n_future_moons == 0){
    return(moons)
  }
  get_future_moons(moons, control$n_future_moons) %>% 
  classy(c("data.frame", "moons")) %>% 
  add_addl_future_moons(control) %>%
  mutate(newmoondate = as.character(newmoondate)) %>%
  bind_rows(moons, .)

}

#' @rdname prep_moons
#'
#' @export
#' 
add_addl_future_moons <- function(future_moons, control = list()){
  control <- do.call("moons_control", control)
  cast_date <- control$cast_date
  n_addl_future_moons <- length(which(future_moons$newmoondate < cast_date))
  if (n_addl_future_moons > 0){
    addl_moons <- get_future_moons(future_moons, n_addl_future_moons)
    future_moons <- bind_rows(future_moons, addl_moons)
  } 
  future_moons
}

#' @title Format the moon data
#'
#' @description Enforce the \code{year} and \code{month} columns and encode 
#'   \code{newmoondate} as a \code{\link{Date}}.
#'
#' @param moons Moons data table as a code{moons}-class \code{data.frame}.
#'
#' @return Moons data table as a code{moons}-class \code{data.frame} with
#'   force-formatted columns. 
#'
#' @export
#' 
format_moons <- function(moons){
  check_args()
  moons$year <- year(moons$newmoondate)
  moons$month <- month(moons$newmoondate)
  moons$newmoondate <- as.Date(moons$newmoondate)
  moons
}
