#' @title Prepare Covariate Data for Casting
#'
#' @description Prepare and combine the historical and cast covariate data for a model run. \cr \cr 
#'              \code{prep_historical_covariates} and \code{prep_forecast_covariates} ready the historical and -casted covariates, respectively. \cr \cr
#'              \code{prep_covariates} combines \code{prep_historical_covariates} and \code{prep_forecast_covariates}.
#'
#' @param main \code{character} value of the name of the main component of the directory tree.
#'
#' @param settings \code{list} of controls for the directory, with defaults set in \code{\link{directory_settings}} that should generally not need to be altered.
#'
#' @return \code{data.frame} of historical and/or -casted covariates that is also saved out to \code{settings$files$covariates} if indicated by \code{settings$save}.
#'  
#' @details \code{prep_historical_covariates} creates a \code{data.frame} of historical weather (\code{\link[portalr]{weather}}) and NDVI data (\code{\link[portalr]{ndvi}}). Automatically goes all the way back to the beginning of the available data, as the table is trimmed later as needed. NDVI data are generated by \code{\link[portalr]{ndvi}}. \cr \cr
#'          \code{prep_forecast_covariates} combines the NMME climate forecasts (\code{\link{download_climate_forecasts}}) with NDVI forecasts using a seasonal auto-ARIMA model on the most resolved and resources data available via (\code{\link[portalr]{ndvi}}). 
#'
#' @examples
#'  \donttest{
#'   setup_dir()
#'   prep_covariates()
#'  }
#'  
#' @name prepare covariates
#'
#' @export
#'
prep_covariates <- function (main     = ".", 
                             settings = directory_settings(), 
                             origin   = Sys.Date(), 
                             quiet    = TRUE, 
                             verbose  = FALSE) {


  messageq("  - covariate data files", quiet = quiet)

  historic_covariates <- prep_historic_covariates(main     = main, 
                                                  settings = settings, 
                                                  quiet    = quiet, 
                                                  verbose  = verbose)
  forecast_covariates <- prep_forecast_covariates(main     = main,
                                                  origin   = origin, 
                                                  settings = settings, 
                                                  quiet    = quiet, 
                                                  verbose  = verbose)

  write_data(dfl       = rbind(historic_covariates, forecast_covariates), 
             main      = main, 
             save      = settings$save, 
             filename  = settings$files$covariates, 
             overwrite = settings$overwrite, 
             quiet     = !verbose)

}


#' @rdname prepare-covariates
#'
#' @export
#'
prep_historic_covariates <- function (main     = ".", 
                                      settings = directory_settings(), 
                                      quiet    = TRUE, 
                                      verbose  = FALSE) {

  weather_data   <- weather(level = "daily", fill = TRUE, path = file.path(main, settings$subs$resources))
  ndvi_data      <- ndvi(level = "daily", path = file.path(main, settings$subs$resources))
  ndvi_data$date <- as.Date(ndvi_data$date)

  out             <- weather_data
  out$source      <- "historic"
  out$ndvi        <- NA
  out$ndvi_source <- NA

  ndvi_dates_in_weather <- na.omit(match(ndvi_data$date, weather_data$date))
  ndvi_dates_to_keep    <- ndvi_data$date %in% weather_data$date

  out$ndvi[ndvi_dates_in_weather]        <- ndvi_data$ndvi[ndvi_dates_to_keep]
  out$ndvi_source[ndvi_dates_in_weather] <- ndvi_data$source[ndvi_dates_to_keep]

  moons <- read_moons(main = main, settings = settings)

  out <- add_newmoonnumbers_from_dates(df = out, moons = moons)

  cols_to_keep <- c("date", "mintemp", "maxtemp", "meantemp", "precipitation", "source", "ndvi", "ndvi_source", "newmoonnumber")

  write_data(dfl       = out[ , cols_to_keep], 
             main      = main, 
             save      = settings$save, 
             filename  = settings$files$historical_covariates, 
             overwrite = settings$overwrite, 
             quiet     = !verbose)

}

#' @rdname prepare-covariates
#'
#' @export
#'
prep_forecast_covariates <- function (main      = ".", 
                                      origin    = Sys.Date(), 
                                      settings  = directory_settings(), 
                                      quiet     = TRUE,
                                      verbose   = FALSE) {

  if (origin == Sys.Date()) {

    climate_forecasts <- read_climate_forecasts(main = main)

    ndvi_data      <- ndvi(level = "daily", path = file.path(main, settings$subs$resources))
    ndvi_data$date <- as.Date(ndvi_data$date)
 
    date_fit     <- ndvi_data$date
    jday_fit     <- as.numeric(format(date_fit, "%j"))
    yr_fit       <- format(date_fit, "%Y")
    nye_fit      <- as.Date(paste(yr_fit, "-12-31", sep = ""))
    nye_jday_fit <- as.numeric(format(nye_fit, "%j"))
    fr_of_yr_fit <- jday_fit/nye_jday_fit
    cos_fit      <- cos(2 * pi * fr_of_yr_fit)
    sin_fit      <- sin(2 * pi * fr_of_yr_fit)
    xreg_fit     <- data.frame(cos_seas = cos_fit, sin_seas = sin_fit)
    xreg_fit     <- as.matrix(xreg_fit)

    ndvi_model   <- auto.arima(ndvi_data$ndvi, xreg = xreg_fit)

    date_fcast     <- climate_forecasts$date
    jday_fcast     <- as.numeric(format(date_fcast, "%j"))
    yr_fcast       <- format(date_fcast, "%Y")
    nye_fcast      <- as.Date(paste(yr_fcast, "-12-31", sep = ""))
    nye_jday_fcast <- as.numeric(format(nye_fcast, "%j"))
    fr_of_yr_fcast <- jday_fcast/nye_jday_fcast
    cos_fcast      <- cos(2 * pi * fr_of_yr_fcast)
    sin_fcast      <- sin(2 * pi * fr_of_yr_fcast)
    xreg_fcast     <- data.frame(cos_seas = cos_fcast, sin_seas = sin_fcast)
    xreg_fcast     <- as.matrix(xreg_fcast)

    ndvi_forecast <- forecast(ndvi_model, xreg = xreg_fcast)

    climate_forecasts$ndvi <- as.numeric(ndvi_forecast$mean)

    out <- climate_forecasts 

  } else {

    # removed for the time being
    stop(" retrieval of pre-existing covariate data not presently available!")

  }

  out$source      <- "forecast" 
  out$ndvi_source <- "forecast" 
  moons           <- read_moons(main = main, settings = settings)
  out             <- add_newmoonnumbers_from_dates(df = out, moons = moons)

  write_data(dfl       = out, 
             main      = main, 
             save      = settings$save, 
             filename  = settings$files$forecast_covariates, 
             overwrite = settings$overwrite, 
             quiet     = !verbose)

}

#' @title Lag covariate data
#'
#' @description Lag the covariate data together based on the new moons
#'
#' @param covariates \code{data.frame} of covariate data to be lagged. 
#'  
#' @param lag \code{integer} lag between rodent census and covariate data, in new moons.
#'  
#' @param tail \code{logical} indicator if the data lagged to the tail end should be retained.
#'
#' @return \code{data.frame} with a \code{newmoonnumber} column reflecting the lag.
#'
#' @examples
#'  \donttest{
#'   setup_dir()
#'   covariate_casts <- read_covariate_casts()
#'   covar_casts_lag <- lag_covariates(covariate_casts, lag = 2, tail = TRUE)
#'  }
#'
#' @export
#'
lag_covariates <- function (covariates, 
                            lag, 
                            tail = FALSE){

  covariates$moon_lag <- covariates$newmoonnumber + lag
  
  if (tail == FALSE) {

    oldest_included_moon     <- covariates$newmoonnumber[1]
    most_recent_moon         <- covariates$newmoonnumber[nrow(covariates)]
    hist_moons               <- oldest_included_moon:most_recent_moon
    moon_match               <- match(covariates$moon_lag, hist_moons)
    covariates$newmoonnumber <- hist_moons[moon_match]
    if (lag > 0) {
      covariates <- covariates[-(1:lag), ]
    }

  }

  covariates$newmoonnumber <- covariates$moon_lag
  covariates$moon_lag      <- NULL
  covariates

}

