
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: test-for-curl

jobs:
  container_check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:

      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: weecology/portalcasting
          tags: |
            type=raw,value=latest

      - name: Build 
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: docker/Dockerfile
          build-args: |
            "event_sha=${{ github.sha }}"

      - name: Test image
        run: |
          docker run weecology/portalcasting:latest curl --manual
